Improve hash->name without reader
leoetlino/aamp pull request #4
Opened 2019-11-13 15:06 UTC by NiceneNerd

I looked more closely at how the AAMP reader is used in `_get_pstruct_name` and realized that I could keep most of the code to get names even without the reader, rather than just skipping to returning the hash.

2019-11-14 02:28 UTC, NiceneNerd commented
Decided to go ahead and push the AAMP<->JSON stuff, too.

2019-11-16 19:53 UTC, leoetlino requested changes

2019-11-16 19:53 UTC, leoetlino commented on aamp/json_util.py
> +        if o['lists']:
This is partially a duplicate of self._to_plist. Maybe consider moving the shared logic into a separate internal function to avoid duplicating code

2019-11-16 19:53 UTC, leoetlino commented on aamp/json_main.py
> +    output.write(aamp.Writer(pio).get_bytes()) # this is on purpose; I got an error using aamp.Writer().write(output)
"I" is unclear where there is more than one contributor ;)

2019-11-24 07:04 UTC, NiceneNerd commented
So, given our conversation on the JSON stuff, I removed it but would still be interested in seeing the minor fix here implemented if possible.

2019-11-24 11:23 UTC, leoetlino approved these changes

2019-11-24 11:23 UTC, merged